# This file is a template, and might need editing before it works on your project.
FROM python:3.7

RUN mkdir /opt/project
WORKDIR /opt/project
COPY . /opt/project

RUN pip install --no-cache-dir -r requirements.txt

# For some other commands
# CMD ["python", "app.py"]
