#!/usr/bin/env python3
"""Compute optimal TurboQuant centroids for d=32 via Lloyd's algorithm.

After randomized Hadamard rotation, each coordinate of a unit-norm d=32 vector
follows the Beta distribution:
    f(x) = Gamma(d/2) / (sqrt(pi) * Gamma((d-1)/2)) * (1 - x^2)^((d-3)/2)

For d=32 this is well-approximated by N(0, 1/d). We solve the continuous
1D k-means (Lloyd's algorithm) against this distribution.

Output: C static arrays for centroids and decision boundaries.
"""
import numpy as np
from scipy import integrate, special

D = 32  # block size

def beta_pdf(x):
    """PDF of a single coordinate of a randomly rotated unit vector in R^d."""
    if abs(x) >= 1.0:
        return 0.0
    c = special.gamma(D / 2) / (np.sqrt(np.pi) * special.gamma((D - 1) / 2))
    return c * (1 - x * x) ** ((D - 3) / 2)

def lloyd_1d(n_centroids, pdf, lo=-1.0, hi=1.0, max_iter=200, tol=1e-12):
    """Solve continuous 1D k-means via Lloyd's algorithm."""
    # Initial centroids: evenly spaced quantiles
    xs = np.linspace(lo + 1e-10, hi - 1e-10, 10000)
    cdf_vals = []
    running = 0.0
    for x in xs:
        running += pdf(x) * (xs[1] - xs[0])
        cdf_vals.append(running)
    cdf_vals = np.array(cdf_vals) / cdf_vals[-1]

    quantiles = np.linspace(1 / (2 * n_centroids), 1 - 1 / (2 * n_centroids), n_centroids)
    centroids = np.interp(quantiles, cdf_vals, xs)

    for iteration in range(max_iter):
        boundaries = [(centroids[i] + centroids[i + 1]) / 2 for i in range(n_centroids - 1)]
        boundaries = [lo] + boundaries + [hi]

        new_centroids = np.zeros(n_centroids)
        for i in range(n_centroids):
            b_lo, b_hi = boundaries[i], boundaries[i + 1]
            num, _ = integrate.quad(lambda x: x * pdf(x), b_lo, b_hi)
            den, _ = integrate.quad(pdf, b_lo, b_hi)
            new_centroids[i] = num / den if den > 1e-15 else (b_lo + b_hi) / 2

        if np.max(np.abs(new_centroids - centroids)) < tol:
            centroids = new_centroids
            break
        centroids = new_centroids

    boundaries = [(centroids[i] + centroids[i + 1]) / 2 for i in range(n_centroids - 1)]
    return centroids, boundaries

def compute_mse(centroids, boundaries, pdf, lo=-1.0, hi=1.0):
    n = len(centroids)
    bounds = [lo] + list(boundaries) + [hi]
    mse = 0.0
    for i in range(n):
        val, _ = integrate.quad(lambda x, c=centroids[i]: (x - c) ** 2 * pdf(x), bounds[i], bounds[i + 1])
        mse += val
    return mse

if __name__ == "__main__":
    print(f"// TurboQuant centroids for d={D} (Beta distribution)")
    print(f"// Generated by compute_centroids.py")
    print()

    for bits in [2, 3, 4]:
        n = 2 ** bits
        centroids, boundaries = lloyd_1d(n, beta_pdf)
        mse = compute_mse(centroids, boundaries, beta_pdf)

        print(f"// {bits}-bit: {n} centroids, MSE = {mse:.10f}")
        c_str = ", ".join(f"{c: .10f}f" for c in centroids)
        print(f"static const float tbq_centroids_{bits}bit[{n}] = {{ {c_str} }};")

        b_str = ", ".join(f"{b: .10f}f" for b in boundaries)
        print(f"static const float tbq_boundaries_{bits}bit[{n - 1}] = {{ {b_str} }};")
        print()
